### ISSUE TITLE
Done button styling

### ISSUE THREAD

**Issue by cmckni3** [exercism/exercism.io#1668]
The styling on the submit button with the text "OK, I'm done. I don't need any more feedback on this." is missing. It appears that the `btn` class may have been removed. Also, I noticed that `bootstrap.css` and `app.css` have the following application specific code.

``` css
button.btn.exercise-done{
  position:relative;
  bottom:20px;
}
```

Any thoughts about adding the `btn` and `btn-default` class back to that submit button and gutting these styles?

P.S. I don't think the `bootstrap.css` file should have been touched to add application styles.

_EDIT_ After looking at the code, the `class` attribute is specified twice.
