### ISSUE TITLE
Typographic Treatment

### ISSUE THREAD

**Issue by lambdahands** [exercism/exercism.io#2038]
Hi! First off, I'd like to say: I'm loving this project and have had a wonderful experience so far. Not only has it greatly assisted in learning new languages, but I've even furthered my own understanding with the tools I use every day.

I've noticed a few design changes over the past few months, and it's looking great so far, but I'd like to add a few notes on the readability of the site as a whole:

The paragraph type is `14px, sans-serif` which is pretty difficult to digest on a screen; the leading (or `line-height` property in CSS) may attribute to this, but it's often best to at least bump up the size to `16px` (or if you set up your main stylesheet as: `body { font-size: 16px }`, you can begin to use `ems` – so `16px` becomes `1em`). Personally, I'd also recommend a serif face to add to readability.

Actually, you're reading this in `14px` type! The difference being greater leading; however, these comments and a website's main copy don't serve the same purpose. For example, I navigated to the [about page](http://exercism.io/about) and entered these styles into a Chrome inspector stylesheet:

```css
.main p {
  font-family: Georgia;
  font-size: 16px;
  line-height: 24px;
  margin-bottom: 16px;
}

.main h4 {
  font-size: 24px ;
  margin-bottom: 16px;
}
```

Georgia is a pretty common serif face (not the most _exiting_ one on the web as it's so ubiquitous), but I think the difference is rather striking.

Here's another block of code I added in the inspector on the [getting started page](http://exercism.io/getting-started):

```css
.article-block p {
  font-family: Georgia;
  font-size: 16px;
  line-height: 24px;
  margin-bottom: 16px;
}

.article-block .header {
  border-bottom: 1px solid #eee;
  padding-bottom: 12px;
  font-size: 28px ;
  margin: 24px 0 16px;
}
```

Mind you, this is purely my design opinion, nothing else; I'd love to hear your two cents on the matter because I believe this project is worth the effort to build a consistent and beautiful user experience.

Thoughts?
