### ISSUE TITLE
Add a python icon

### ISSUE THREAD

**Issue by jdost** [exercism/exercism.io#498]
Right now, the Python projects on the site have no icon next to the projects.  The CSS needs something like:

``` css
.python-icon {
    background-image: url(/img/python.png);
}
```

You could use:
![Python Logo, w/o text](http://pytoexe.sourceforge.net/dosyalar/python_logo_without_textsvg.png)
